# File format: https://pre-commit.com/#plugins
# Supported hooks: https://pre-commit.com/hooks.html
# Running "make format" fixes most issues for you
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--quiet, --exclude, src/tests]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: migrations/
        additional_dependencies:
          - flake8-blind-except == 0.1.1
          - flake8-debugger == 3.2.1
          - flake8-colors == 0.1.6
          - flake8-raise == 0.0.5

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--filter-files"]

#  - repo: https://github.com/prettier/prettier
#    rev: "1.19.1"
#    hooks:
#      - id: prettier
#        files: '\.(js|ts|jsx|tsx|scss|css|yml|yaml|json)$'
