# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
sphinx:
   configuration: dev-docs/source/conf.py
formats: []

# Not needed yet because of conf.py hack:
#build:
#  apt_packages:
#    - libgdal20
#    - libproj13

python:
   version: 3.9
   install:
   - requirements: dev-docs/requirements.txt
