FROM amsterdam/python:3.8-buster AS builder

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      graphviz \
      fonts-liberation \
      make \
      git \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp/docs
COPY dev-docs/ /tmp/docs/
COPY src/ /tmp/src/
RUN pip install -r /tmp/docs/requirements.txt

# Added arg here, so build step is invalidated each time
ARG BUILD_NUMBER=unknown
RUN mkdir -p /tmp/docs/_static \
 && make html

# Static serving runtime
FROM nginx
RUN mkdir -p /usr/share/nginx/html/v1/docs/
COPY --from=builder /tmp/docs/build/html/ /usr/share/nginx/html/
