services:
  database:
    image: postgis/postgis:14-3.2
    restart: always
    user: postgres
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 20s
    ports:
       - "5415:5432"
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: insecure
    command: ["postgres", "-c", "log_statement=all"]

  web:
    build:
      context: src/
      args:
        PIP_REQUIREMENTS: requirements_dev.txt
    ports:
      - "8090:8000"
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    environment:
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "dso_api.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/dso_api/static=/static"
      SECRET_KEY: insecure
      BULK_ENDPOINT: "${BULK_ENDPOINT:-https://api.data-o.azure.amsterdam.nl/bulk-data}"
      CONFIDENTIAL_BULK_ENDPOINT: "${CONFIDENTIAL_BULK_ENDPOINT:-https://api.data-o.azure.amsterdam.nl/buk-data-fp-mdw}"
      DATABASE_URL: "${DATABASE_URL:-postgresql://postgres:insecure@database/dataservices}"
      DJANGO_LOG_LEVEL: "${DJANGO_LOG_LEVEL:-INFO}"
      DSO_API_LOG_LEVEL: "${DSO_API_LOG_LEVEL:-INFO}"
      DSO_API_AUDIT_LOG_LEVEL: "${DSO_API_AUDIT_LOG_LEVEL:-INFO}"
      AZURE_APPI_AUDIT_CONNECTION_STRING: "${AZURE_APPI_AUDIT_CONNECTION_STRING}"
      AZURE_APPI_CONNECTION_STRING: "${AZURE_APPI_CONNECTION_STRING}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_JWKS_URL: "${OAUTH_JWKS_URL}"
      PUB_JWKS: "$(cat src/jwks_test.json)"
      OAUTH_URL:  "${OAUTH_URL}"
      CLOUD_ENV: "${CLOUD_ENV}"
      DATAPUNT_API_URL: "${DATAPUNT_API_URL}"
      DJANGO_DEBUG: 1
      APIKEY_ENABLED: "${APIKEY_ENABLED}"
      INITIALIZE_DB: "${INITIALIZE_DB:-true}"
      MOCK_DATA: "${MOCK_DATA:-false}"
      SCHEMA_URL: "${SCHEMA_URL:-https://schemas.data.amsterdam.nl/datasets/}"
      DATASETS_LIST: "${DATASETS_LIST}"
      DATASETS_EXCLUDE: "${DATASETS_EXCLUDE}"
    volumes:
      - ./src:/app
      - ./docs/build/html:/docs-static
      - "../amsterdam-schema/datasets:/tmp/datasets"
      - "../schema-tools:/tmp/schema-tools"
    command: >
      /bin/bash -c "sh /app/initialize_db.sh
      && uwsgi --py-auto-reload=1 --enable-threads --lazy-apps --buffer-size=65535"
