version: "3.7"
services:
  # This Postgres container is used for testing by Jenkins.
  # The actual deployment uses a database configured separately.
  # For development, use the one from dataservices-airflow;
  # see dev-docs/source/howto/install.rst.
  database:
    image: postgis/postgis:14-3.2
    restart: always
    user: postgres
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 1s  
    ports:
       - "5415:5432"
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: insecure
    command: ["postgres", "-c", "log_statement=all"]

  web:
    build:
      context: src/
      args:
        PIP_REQUIREMENTS: requirements_dev.txt
    ports:
      - "8090:8000"
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    environment:
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "dso_api.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/dso_api/static=/static"
      SECRET_KEY: insecure
      DATABASE_URL: "${DATABASE_URL:-postgres://postgres:insecure@database/dataservices}"
      DJANGO_LOG_LEVEL: "${DJANGO_LOG_LEVEL}"
      DSO_API_LOG_LEVEL: "${DSO_API_LOG_LEVEL}"
      DSO_API_AUDIT_LOG_LEVEL: "${DSO_API_AUDIT_LOG_LEVEL}"
      AZURE_APPI_AUDIT_CONNECTION_STRING: "${AZURE_APPI_AUDIT_CONNECTION_STRING}"
      AZURE_APPI_CONNECTION_STRING: "${AZURE_APPI_CONNECTION_STRING}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_JWKS_URL: "${OAUTH_JWKS_URL}"
      OAUTH_URL:  "${OAUTH_URL}"
      CLOUD_ENV: "${CLOUD_ENV}"
      DATAPUNT_API_URL: "${DATAPUNT_API_URL}"
      DJANGO_DEBUG: 1
      APIKEY_ENABLED: "${APIKEY_ENABLED}"
    volumes:
      - ./src:/app
      - ./docs/build/html:/docs-static
      - "../amsterdam-schema/datasets:/tmp/datasets"
      - "../schema-tools:/tmp/schema-tools"
    command: uwsgi --py-auto-reload=1 --enable-threads --lazy-apps --buffer-size=65535

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  schemas:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./schemas/data/datasets:/usr/share/nginx/html/datasets"
      - "./schemas/conf/default.conf:/etc/nginx/conf.d/default.conf"
