version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5415:5432"
    environment:
      POSTGRES_DB: dso_api
      POSTGRES_USER: dso_api
      POSTGRES_PASSWORD: insecure
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
      - .:/host
  web:
    build: src/
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "dso_api.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/dso_api/static=/static"
      SECRET_KEY: insecure
      DATABASE_URL: "postgres://dso_api:insecure@database/dso_api"
    volumes:
      - ./src:/app
    command: uwsgi --py-auto-reload=1
