version: "3.0"
services:
  owasp:
    image: owasp/zap2docker-stable  
    ports:      
      - "8090:8090"
    command: > 
      bash -c "zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true && .jenkins/owasp_vulnerability_scan/owasp_scan.sh" 