version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: dataservices
      POSTGRES_PASSWORD: insecure
  
  owasp:
    image: owasp/zap2docker-stable  
    ports:      
      - "8090:8090"
    networks:
      - owasp
    command: zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true 

  test:
    build: ../..
    links:
      - database
      - owasp
    networks:
      - owasp
    environment:
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "dso_api.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/dso_api/static=/static"
      SECRET_KEY: insecure
      DATABASE_URL: "postgres://dataservices:insecure@database/dataservices"
    command: >
      bash -c ".jenkins/owasowasp_vulnerability_scan/owasp_scan.sh"
  
networks:
  owasp:
  
      