# All commented out lines in this file are needed for debugging puproses.
version: "3.0"
services:
  owasp:
    image: owasp/zap2docker-stable:2.11.1
    ports:      
      - "8090:8090"
    networks:
      - owasp
    # links:
    #   - web
    command: zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true 

  test:
    build: ../..
    links:   
      - owasp
    #   - web
    networks:
      - owasp   
    environment:
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "dso_api.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/dso_api/static=/static"
      SECRET_KEY: insecure
      DATABASE_URL: "postgres://dataservices:insecure@database/dataservices"
    command: >
      bash -c ".jenkins/owasp_vulnerability_scan/owasp_scan.sh"
    # volumes:
    #   - ../../:/app

  # Local development goodies.
  # database:
  #   image: amsterdam/postgres11
  #   ports:
  #     - "5415:5432"
  #   networks:
  #     - owasp
  #   environment:
  #     POSTGRES_DB: dataservices
  #     POSTGRES_USER: dataservices
  #     POSTGRES_PASSWORD: insecure
  #   volumes:
  #     - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
  #     - .:/host
  #   extra_hosts:
  #     admin.data.amsterdam.nl: 10.243.16.4
  #
  # web:
  #   build:
  #     context: ../../
  #     args:
  #       PIP_REQUIREMENTS: requirements_dev.txt
  #   ports:
  #     - "8000:8000"
  #   links:
  #     - database
  #   networks:
  #     - owasp
  #   environment:
  #     UWSGI_HTTP_SOCKET: ":8000"
  #     UWSGI_MODULE: "dso_api.wsgi"
  #     UWSGI_CALLABLE: "application"
  #     UWSGI_MASTER: 1
  #     UWSGI_STATIC_MAP: "/dso_api/static=/static"
  #     SECRET_KEY: insecure
  #     DATABASE_URL: "postgres://dataservices:insecure@database/dataservices"
  #     DJANGO_DEBUG: 1
  #   volumes:
  #     - ../../:/app
  #     - ./docs/build/html:/docs-static
  #   command: uwsgi --py-auto-reload=1
  
networks:
  owasp:
