name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - master
      - timo/fix-ado-pipeline-call

jobs:
    build:
        name: Call Build AKS Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Call Azure
          uses: tlrh314/pipelines@v2.0
          with:
            azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_URL }}
            azure-pipeline-name: ${{ secrets.AZURE_DEVOPS_PIPELINE }}
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
            azure-pipeline-variables: '{ "environment" : "test", "solution" : "central", "runBuildPush": "True", "runContainerScan" : "True" }'
