name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - master

jobs:
    build:
        name: Call Build AKS Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Call Azure
          uses: amsterdam/trigger-ado-pipeline@v1
          with:
            pipeline-id: 751
            organisation: CloudCompetenceCenter
            project: 'Data Diensten'
            pat-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
            template-params: '{"environments": "- dev\n- prd", "branch": "master", "akscluster": "blue"}'
