name: Run Pytest
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
    - features/**
  pull_request:
    branches:
    - main
    - master

jobs:
  tests:
    # Run tests for different PostGIS versions while we work on migrating the db.
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        postgis_version:
        - 14-3.2
        - 17-3.5
    env:
      INITIALIZE_DB: false
      POSTGIS_VERSION: ${{ matrix.postgis_version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d --build

    - name: Run tests
      run: docker compose exec -T web pytest -v --ds=tests.settings --show-capture=no --cov --cov-report=term:skip-covered --cov-config=.coveragerc

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down
